// Prefix keys with 'justinlietz93.apex.' to ensure uniqueness
export type SecretKey =
	| "justinlietz93.apex.apiKey"
	| "justinlietz93.apex.apexApiKey"
	| "justinlietz93.apex.openRouterApiKey"
	| "justinlietz93.apex.awsAccessKey"
	| "justinlietz93.apex.awsSecretKey"
	| "justinlietz93.apex.awsSessionToken"
	| "justinlietz93.apex.openAiApiKey"
	| "justinlietz93.apex.geminiApiKey"
	| "justinlietz93.apex.openAiNativeApiKey"
	| "justinlietz93.apex.deepSeekApiKey"
	| "justinlietz93.apex.requestyApiKey"
	| "justinlietz93.apex.togetherApiKey"
	| "justinlietz93.apex.qwenApiKey"
	| "justinlietz93.apex.mistralApiKey"
	| "justinlietz93.apex.liteLlmApiKey"
	| "justinlietz93.apex.authNonce"
	| "justinlietz93.apex.asksageApiKey"
	| "justinlietz93.apex.xaiApiKey"
	| "justinlietz93.apex.sambanovaApiKey"
export type GlobalStateKey =
	| "justinlietz93.apex.apiProvider"
	| "justinlietz93.apex.apiModelId"
	| "justinlietz93.apex.awsRegion"
	| "justinlietz93.apex.awsUseCrossRegionInference"
	| "justinlietz93.apex.awsBedrockUsePromptCache"
	| "justinlietz93.apex.awsBedrockEndpoint"
	| "justinlietz93.apex.awsProfile"
	| "justinlietz93.apex.awsUseProfile"
	| "justinlietz93.apex.vertexProjectId"
	| "justinlietz93.apex.vertexRegion"
	| "justinlietz93.apex.lastShownAnnouncementId"
	| "justinlietz93.apex.customInstructions"
	| "justinlietz93.apex.taskHistory"
	| "justinlietz93.apex.openAiBaseUrl"
	| "justinlietz93.apex.openAiModelId"
	| "justinlietz93.apex.openAiModelInfo"
	| "justinlietz93.apex.ollamaModelId"
	| "justinlietz93.apex.ollamaBaseUrl"
	| "justinlietz93.apex.ollamaApiOptionsCtxNum"
	| "justinlietz93.apex.lmStudioModelId"
	| "justinlietz93.apex.lmStudioBaseUrl"
	| "justinlietz93.apex.anthropicBaseUrl"
	| "justinlietz93.apex.azureApiVersion"
	| "justinlietz93.apex.openRouterModelId"
	| "justinlietz93.apex.openRouterModelInfo"
	| "justinlietz93.apex.openRouterProviderSorting"
	| "justinlietz93.apex.autoApprovalSettings"
	| "justinlietz93.apex.browserSettings"
	| "justinlietz93.apex.chatSettings"
	| "justinlietz93.apex.vsCodeLmModelSelector"
	| "justinlietz93.apex.userInfo"
	| "justinlietz93.apex.previousModeApiProvider"
	| "justinlietz93.apex.previousModeModelId"
	| "justinlietz93.apex.previousModeThinkingBudgetTokens"
	| "justinlietz93.apex.previousModeVsCodeLmModelSelector"
	| "justinlietz93.apex.previousModeModelInfo"
	| "justinlietz93.apex.liteLlmBaseUrl"
	| "justinlietz93.apex.liteLlmModelId"
	| "justinlietz93.apex.qwenApiLine"
	| "justinlietz93.apex.requestyModelId"
	| "justinlietz93.apex.togetherModelId"
	| "justinlietz93.apex.mcpMarketplaceCatalog"
	| "justinlietz93.apex.telemetrySetting"
	| "justinlietz93.apex.asksageApiUrl"
	| "justinlietz93.apex.thinkingBudgetTokens"
	| "justinlietz93.apex.planActSeparateModelsSetting"
	// Keys for Local Profiles & Custom Instruction Library
	| "justinlietz93.apex.userProfiles" // Stores array of UserProfile objects
	| "justinlietz93.apex.activeProfileId" // Stores the ID of the active profile
	| "justinlietz93.apex.customInstructionLibrary" // Stores array of CustomInstructionItem objects
